// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Changes is the predicate function for changes builders.
type Changes func(*sql.Selector)

// Entity is the predicate function for entity builders.
type Entity func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)
