// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (c *ChangesQuery) CollectFields(ctx context.Context, satisfies ...string) *ChangesQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		c = c.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return c
}

func (c *ChangesQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *ChangesQuery {
	return c
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (h *HistoryQuery) CollectFields(ctx context.Context, satisfies ...string) *HistoryQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		h = h.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return h
}

func (h *HistoryQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *HistoryQuery {
	return h
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (t *TweetQuery) CollectFields(ctx context.Context, satisfies ...string) *TweetQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		t = t.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return t
}

func (t *TweetQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *TweetQuery {
	return t
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (u *UserQuery) CollectFields(ctx context.Context, satisfies ...string) *UserQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		u = u.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return u
}

func (u *UserQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *UserQuery {
	return u
}
