// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ariga/edit-twitter-example-app/enthistory/ent/changes"
	"github.com/ariga/edit-twitter-example-app/enthistory/ent/history"
	"github.com/ariga/edit-twitter-example-app/enthistory/ent/predicate"
)

// ChangesUpdate is the builder for updating Changes entities.
type ChangesUpdate struct {
	config
	hooks    []Hook
	mutation *ChangesMutation
}

// Where appends a list predicates to the ChangesUpdate builder.
func (cu *ChangesUpdate) Where(ps ...predicate.Changes) *ChangesUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetColumn sets the "column" field.
func (cu *ChangesUpdate) SetColumn(s string) *ChangesUpdate {
	cu.mutation.SetColumn(s)
	return cu
}

// SetValue sets the "value" field.
func (cu *ChangesUpdate) SetValue(s string) *ChangesUpdate {
	cu.mutation.SetValue(s)
	return cu
}

// SetPrevious sets the "previous" field.
func (cu *ChangesUpdate) SetPrevious(s string) *ChangesUpdate {
	cu.mutation.SetPrevious(s)
	return cu
}

// SetNillablePrevious sets the "previous" field if the given value is not nil.
func (cu *ChangesUpdate) SetNillablePrevious(s *string) *ChangesUpdate {
	if s != nil {
		cu.SetPrevious(*s)
	}
	return cu
}

// ClearPrevious clears the value of the "previous" field.
func (cu *ChangesUpdate) ClearPrevious() *ChangesUpdate {
	cu.mutation.ClearPrevious()
	return cu
}

// SetOperationID sets the "operation" edge to the History entity by ID.
func (cu *ChangesUpdate) SetOperationID(id int) *ChangesUpdate {
	cu.mutation.SetOperationID(id)
	return cu
}

// SetNillableOperationID sets the "operation" edge to the History entity by ID if the given value is not nil.
func (cu *ChangesUpdate) SetNillableOperationID(id *int) *ChangesUpdate {
	if id != nil {
		cu = cu.SetOperationID(*id)
	}
	return cu
}

// SetOperation sets the "operation" edge to the History entity.
func (cu *ChangesUpdate) SetOperation(h *History) *ChangesUpdate {
	return cu.SetOperationID(h.ID)
}

// Mutation returns the ChangesMutation object of the builder.
func (cu *ChangesUpdate) Mutation() *ChangesMutation {
	return cu.mutation
}

// ClearOperation clears the "operation" edge to the History entity.
func (cu *ChangesUpdate) ClearOperation() *ChangesUpdate {
	cu.mutation.ClearOperation()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChangesUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChangesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChangesUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChangesUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChangesUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ChangesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   changes.Table,
			Columns: changes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: changes.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Column(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: changes.FieldColumn,
		})
	}
	if value, ok := cu.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: changes.FieldValue,
		})
	}
	if value, ok := cu.mutation.Previous(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: changes.FieldPrevious,
		})
	}
	if cu.mutation.PreviousCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: changes.FieldPrevious,
		})
	}
	if cu.mutation.OperationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changes.OperationTable,
			Columns: []string{changes.OperationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: history.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.OperationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changes.OperationTable,
			Columns: []string{changes.OperationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: history.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{changes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ChangesUpdateOne is the builder for updating a single Changes entity.
type ChangesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChangesMutation
}

// SetColumn sets the "column" field.
func (cuo *ChangesUpdateOne) SetColumn(s string) *ChangesUpdateOne {
	cuo.mutation.SetColumn(s)
	return cuo
}

// SetValue sets the "value" field.
func (cuo *ChangesUpdateOne) SetValue(s string) *ChangesUpdateOne {
	cuo.mutation.SetValue(s)
	return cuo
}

// SetPrevious sets the "previous" field.
func (cuo *ChangesUpdateOne) SetPrevious(s string) *ChangesUpdateOne {
	cuo.mutation.SetPrevious(s)
	return cuo
}

// SetNillablePrevious sets the "previous" field if the given value is not nil.
func (cuo *ChangesUpdateOne) SetNillablePrevious(s *string) *ChangesUpdateOne {
	if s != nil {
		cuo.SetPrevious(*s)
	}
	return cuo
}

// ClearPrevious clears the value of the "previous" field.
func (cuo *ChangesUpdateOne) ClearPrevious() *ChangesUpdateOne {
	cuo.mutation.ClearPrevious()
	return cuo
}

// SetOperationID sets the "operation" edge to the History entity by ID.
func (cuo *ChangesUpdateOne) SetOperationID(id int) *ChangesUpdateOne {
	cuo.mutation.SetOperationID(id)
	return cuo
}

// SetNillableOperationID sets the "operation" edge to the History entity by ID if the given value is not nil.
func (cuo *ChangesUpdateOne) SetNillableOperationID(id *int) *ChangesUpdateOne {
	if id != nil {
		cuo = cuo.SetOperationID(*id)
	}
	return cuo
}

// SetOperation sets the "operation" edge to the History entity.
func (cuo *ChangesUpdateOne) SetOperation(h *History) *ChangesUpdateOne {
	return cuo.SetOperationID(h.ID)
}

// Mutation returns the ChangesMutation object of the builder.
func (cuo *ChangesUpdateOne) Mutation() *ChangesMutation {
	return cuo.mutation
}

// ClearOperation clears the "operation" edge to the History entity.
func (cuo *ChangesUpdateOne) ClearOperation() *ChangesUpdateOne {
	cuo.mutation.ClearOperation()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChangesUpdateOne) Select(field string, fields ...string) *ChangesUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Changes entity.
func (cuo *ChangesUpdateOne) Save(ctx context.Context) (*Changes, error) {
	var (
		err  error
		node *Changes
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChangesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChangesUpdateOne) SaveX(ctx context.Context) *Changes {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChangesUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChangesUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ChangesUpdateOne) sqlSave(ctx context.Context) (_node *Changes, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   changes.Table,
			Columns: changes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: changes.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Changes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, changes.FieldID)
		for _, f := range fields {
			if !changes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != changes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Column(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: changes.FieldColumn,
		})
	}
	if value, ok := cuo.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: changes.FieldValue,
		})
	}
	if value, ok := cuo.mutation.Previous(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: changes.FieldPrevious,
		})
	}
	if cuo.mutation.PreviousCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: changes.FieldPrevious,
		})
	}
	if cuo.mutation.OperationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changes.OperationTable,
			Columns: []string{changes.OperationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: history.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.OperationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changes.OperationTable,
			Columns: []string{changes.OperationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: history.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Changes{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{changes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
