// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Changes is the predicate function for changes builders.
type Changes func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// Tweet is the predicate function for tweet builders.
type Tweet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
